config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  resources :blogs, only: [:index]

  namespace :api do
    get 'blogs/index', to: 'blogs#index'
    get 'users/create', to: 'users#create'
    get 'sessions/create', to: 'sessions#create'
    post 'login', to: 'sessions#create'
    post 'signup', to: 'users#create'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :blogs
  validates :email, uniqueness: true
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
  end
end

app/controllers/api/blogs_controller.rb
module Api
  class BlogsController < ApplicationController
    before_action :authenticate_user

    def index
      @blogs = @current_user.blogs
      render json: @blogs
    end

    private

    def authenticate_user
      token = request.headers['Authorization']&.split(' ')&.last
      unless token && valid_token?(token)
        render json: { error: 'Authentication required' }, status: :unauthorized
      end
    end


    def valid_token?(token)
      begin
        decoded_token = JWT.decode(token, Rails.application.secrets.secret_key_base, true, algorithm: 'HS256')
        user_id = decoded_token.first['user_id']
        @current_user = User.find_by(id: user_id)
        @current_user.present?
      rescue JWT::DecodeError
        false
      end
    end
  end
end

app/controllers/api/sessions_controller.rb
module Api
  class SessionsController < ApplicationController
    def create
      user = User.find_by(email: params[:user][:email])
      if user && user.authenticate(params[:user][:password])
        jwt_token = generate_jwt(user)
        render json: { message: 'Login successful', user_id: user.id, token: jwt_token }
      else
        render json: { error: 'Invalid email or password' }, status: :unprocessable_entity
      end
    end

    private

    def generate_jwt(user)
      payload = { user_id: user.id }
      JWT.encode(payload, Rails.application.secrets.secret_key_base, 'HS256')
    end
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        render json: { message: 'Registration successful', user_id: @user.id }
      else
        render json: { error: @user.errors.full_messages }, status: :unprocessable_entity
      end
    end

    private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :require_login

  def index
    @blogs = current_user.blogs # Assuming you have a Blog model
  end

  private

  def require_login
    unless current_user
      redirect_to login_path, alert: 'You must be logged in to access this page.'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to blogs_path, notice: 'Login successful!'
    else
      flash.now[:alert] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Registration successful!'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/api/blogs_helper.rb
module Api::BlogsHelper
end

app/helpers/api/sessions_helper.rb
module Api::SessionsHelper
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.content %></td>
        <td><%= book.user.username%> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to "Sign Out", logout_path, method: :delete, class: "nav-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_with(model: @user, url: signup_path) do |form| %>
  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.submit "Register", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Login", login_path %>